### ISSUE TITLE
[Request] A script that converts 1337x timestamps to local timezone 

### ISSUE THREAD

**Issue by NitroV** [darkred/Userscripts#11]
Basically what [this script](https://github.com/darkred/Userscripts/tree/master/RARBG_-_convert_torrent_timestamps_to_relative_format) does, but for 1337x[dot]to instead. Thanks in advance.

**Comment by darkred** [comment]
I don't use the 1337x site.
Howerver, I made a version for you to test: [link](https://gist.github.com/darkred/604e6f68190b14890dd8ce3ce9fb72a9/raw/8b7205a7bbeb406fbd2f7be58869730e55348893/gistfile1.user.js)

Notes: because the timestamps are in 3 formats instead of one (as in rarbg);
- the recalculation them every 10 seconds is disabled, and 
- the tooltip when hovering mouse only displays the initial timestamp, i.e. it's not converted to your timezone.

I won't publish it unless I ever fix these issues.

**Comment by darkred** [comment]
@NitroV Did you try the script ?

**Comment by NitroV** [comment]
> I don't use the 1337x site.
> However, I made a version for you to test: [link](https://gist.github.com/darkred/604e6f68190b14890dd8ce3ce9fb72a9/raw/8b7205a7bbeb406fbd2f7be58869730e55348893/gistfile1.user.js)
> 
> Notes: because the timestamps are in 3 formats instead of one (as in rarbg);
> 
> * the recalculation them every 10 seconds is disabled, and
> * the tooltip when hovering mouse only displays the initial timestamp, i.e. it's not converted to your timezone.
> 
> I won't publish it unless I ever fix these issues.

Thanks a bunch! I did not notice the formats of timestamps are different at first.

> @NitroV Did you try the script ?

I did. I mainly wanted the script to work for search results however it didn't change the original timestamps.

**Comment by darkred** [comment]
> I did. I mainly wanted the script to work for [search results](https://1337x.to/search/search-term-here/1/) however it didn't change the original timestamps, even when [sorted by time desc.](https://1337x.to/sort-search/search-term-here/time/desc/1/) No luck on [home](https://1337x.to/home/) page either.

Those patterns were missing from the `@include` rule added. Update to the [new version](https://gist.github.com/darkred/604e6f68190b14890dd8ce3ce9fb72a9/raw/3948e98260f2bc375e1323f707d25fb7d1e0632b/gistfile1.user.js).

> however in search results, its shown in `hh:mm tt` format for the latest results and then changes to `hh tt MMM. DD` format after the last 24 hours

That was caused by the missing patterns in the `@include` rule, should be fixed now.

> I also figured out the timezone used in 1337x which is utc+1 if that helps.

Are the timestamps are currently to your local timezone ok? Or not and you want me to modify the script?
I use the following in the script:

```
const serverTimezone = 'Etc/GMT-1';  		// +01:00	+01:00  (=no DST)
```

&nbsp; 

Let me know if you notice any other page examples where the script doesn't work.

PS. The gist page URL is [here](https://gist.github.com/darkred/604e6f68190b14890dd8ce3ce9fb72a9) .

**Comment by NitroV** [comment]
> Are the timestamps are currently to your local timezone ok? Or not and you want me to modify the script?
> I use the following in the script:

Well, now the script converts the timestamps from the above pages to `x minutes/hours ago` format however the actual time shown is the same as original, meaning the timezone conversion has not have happened.

For example; a result from search as shown uploaded on 11:17am (in utc+1) **without the script running** is shown 6 hours ago (as of now) **with the script enabled**, which is still in utc+1, it has only change the format 

By utc+1 I meant to say the timezone used in 1337x to display its timestamps by default. I am located in a country that belongs to gmt+530 so the difference should be about 4.5hours ahead of the original utc+1 timestamps

**Comment by darkred** [comment]
As I write in my first comment, for the time being:
> the tooltip when hovering mouse only displays the **initial timestamp**, i.e. it's not converted to your timezone.

but the conversion to local timezone is done ok.

E.g. check a page where there are new entries constantly added: https://1337x.to/cat/XXX/1/

For me the latest result is on `5:56pm`.
Converted to my local timezone is `6:56pm` 
and so it becomes `3 minutes ago`, which is the correct one.
But the tooltip is `5:56pm`.

---

To verify that the guessed "Continent/country" ise the same timezone as your actual one
you may add an `alert(localTimezone)`  right below the `const localTimezone = moment.tz.guess();` line,
and then compare the displayed string against https://en.wikipedia.org/wiki/List_of_tz_database_time_zones .

If it's empty/wrong, then you'll have to add the local timezone to the script manually.

To further clarify, I use the following in the script:

```javascript
// TZ database name: Etc/GMT-1,      
// UTC offset: +01:00,      UTC DST offset: +01:00  (=no DST)
const serverTimezone = 'Etc/GMT-1';  		
```

So, don't confuse the offset with the timezone.
If you are in GMT+530 then the offsets should be:
UTC offset: +05:30,      
UTC DST offset: -05:30(=no DST) or -04:30(=with DST).
GMT+530 doesn't refer to a specific TZ database name,
so you'll have to find a close one, from the wikipedia page I gave you.

**Comment by NitroV** [comment]
You're correct! Sorry for the confusion. I was hoping to see the exact timestamps converted to my timezone in `hh:mm tt` format but I'm happy with the `x amount of time ago` format so far :) Thanks again for the amazing script!

**Comment by NitroV** [comment]
> Let me know if you notice any other page examples where the script doesn't work.

Please have a look at sub-category URLs as well, the script doesn't seem to modify timestamps there;

eg: `https://1337x.to/sub/42/0/` (for movies->hd)

You can find most of the sub-categories on top of main category pages.

`https://1337x.to/cat/Movies/1/` for movies. (script does work here btw)

**Comment by darkred** [comment]
Should be ok now: [new version](https://gist.github.com/darkred/604e6f68190b14890dd8ce3ce9fb72a9/raw/b63f817f0e0c14247b4b9d1ff24b1ae1ca316201/gistfile1.user.js)

> Thanks again for the amazing script!

Glad to be of help.

**Comment by NitroV** [comment]
> Should be ok now

It is! The script works pretty much everywhere in the website so far.

Please have a look at timezone conversion for tooltips as well in the future. Having the `x amount of ago` timestamps by default and tooltips showing the corrected timestamps in `hh:mm tt` format at the same time like the rarbg script would be perfect!

**Comment by darkred** [comment]
Hi. I believe these two features work fine now in the [new version](https://gist.github.com/darkred/604e6f68190b14890dd8ce3ce9fb72a9/raw/1913c6b861254c65b5eab30c1f3b19fbea66a739/gistfile1.user.js)

**Comment by darkred** [comment]
@NitroV Did you try the new version ?

**Comment by NitroV** [comment]
Sorry for the late reply, I just loaded the new version to the script manager and a quick test suggests that the tooltips are now properly converted to the local time zone. Thanks for the followup, much appreciated.

**Comment by NitroV** [comment]
Hello again!
I have an update on new and cleaned up script hosted on this repo, ever since I've switched to the [repo version](https://github.com/darkred/Userscripts/raw/master/1337X_-_convert_torrent_timestamps_to_relative_format/1337X_-_convert_torrent_timestamps_to_relative_format.user.js), I've been getting this creepy popup everytime I search for something from homepage.

![image](https://user-images.githubusercontent.com/73184871/106356271-7b16db00-6324-11eb-8a08-4c6c84139071.png)

I first thought this was implemented by 1337x themselves, but disabling script host extension took that away. And to my surprise I loaded the test script from gist link you shared in one of the above comments, it was gone too. Just to make sure I again loaded repo version and the popup was back when searching. Very weird issue, that I thought might be worth reporting.

**Comment by darkred** [comment]
I had added https://github.com/darkred/Userscripts/issues/11#issuecomment-740057960 that [`alert()`](https://www.w3schools.com/jsref/met_win_alert.asp) in the gist version to assist you in confirming whether the guessed "Continent/City" is the same timezone as your actual one. 

But, I forgot to remove it in the repo, sorry. Fixed in the new version 👍

**Comment by NitroV** [comment]
Oh that explains it. It returned correct values btw, thanks again for the quick fix. will switch back to repo version :)

**Comment by NitroV** [comment]
Hello! I just realized the timezone correction of tooltips have stopped working, it shows the time in og 1337x zone (confirmed by disabling the script)

![image](https://user-images.githubusercontent.com/73184871/106554886-5730e080-6542-11eb-86db-64ef322191ca.png)

Also rarbg shows same release at around 7.55am local (correct) which makes sense since the official lauchtime of that ep was at 7.30 local.

![image](https://user-images.githubusercontent.com/73184871/106554998-b0007900-6542-11eb-9454-4ad264863b42.png)

Please do have a look when you got some free time. Thanks in advance.

**Comment by darkred** [comment]
Both features (converting tooltips to local timezone + recalc) should be working ok in the new version.
