### ISSUE TITLE
[Request] A script that always exclude results from certain countries in imdb advanced title search

### ISSUE THREAD

**Issue by NitroV** [darkred/Userscripts#15]
**Is your feature request related to a problem? Please describe.**

There is no option to exclude results from certain countries in the UI of the [imdb advanced title search page](https://www.imdb.com/search/title/) however this can be achieved by modifying ["countries" parameter in the url](https://community-imdb.sprinklr.com/conversations/imdbcom/exclude-country-in-advanced-search/5f4a79cc8815453dba8b3abb?commentId=5f4a7bc38815453dbae646bb&replyId=5f4a7e158815453dba5211f5).

**Describe the solution you'd like**

Either the script with hardcoded values always inject `&countries=!xy` parameter to every advanced search urls (in my case: =!in) OR modify the function of default "countries" field to EXCLUDE results from selected country instead of only including results from that country.

**Describe alternatives you've considered**

Manually add the countries parameter to every search url :(

**Comment by darkred** [comment]
You may use a simple script that fits your specific criteria, modify it as you like:


```javascript
// ==UserScript==
// @name        imdb advanced title search - always exclude results from certain countries
// @include     https://www.imdb.com/search/title/*
// @grant       none
// ==/UserScript==

// https://www.imdb.com/search/title/?title_type=feature&countries=!af,pk&view=simple&count=250
const countriesToIgnore = '&countries=!af,!pk';  // Here are excluded ones from Afghanistan and Pakistan
if (!window.location.href.includes(countriesToIgnore)) {
	window.location.href += countriesToIgnore;
}
```

For example, if you open e.g.
https://www.imdb.com/search/title/?title=The+Godfather it will change the current url(=redirect you to) to 
https://www.imdb.com/search/title/?title_type=feature&countries=!af,!pk&view=simple&count=250

**Comment by NitroV** [comment]
> You may use a simple script that fits your specific criteria, modify the country codes as you need:
> 
> ```js
> // ==UserScript==
> // @name        imdb advanced title search - always exclude results from certain countries
> // @include     https://www.imdb.com/search/title/*
> // @grant       none
> // ==/UserScript==
> 
> // https://www.imdb.com/search/title/?title_type=feature&countries=!af,pk&view=simple&count=250
> const countriesToIgnore = '&countries=!af,!pk';  // Here the excluded ones are from Afghanistan and Pakistan
> if (!window.location.href.includes(countriesToIgnore)) {
> 	window.location.href += countriesToIgnore;
> }
> ```
> 
> For example, if you open e.g.
> https://www.imdb.com/search/title/?title=The+Godfather it will change the current url(=redirect you to) to
> https://www.imdb.com/search/title/?title=The+Godfather&countries=!af,!pk

Thanks for the quick reply! There's a small problem though, now the [advance title search page](https://www.imdb.com/search/title/) is not accessible to select other parameters (eg: ratings) as it always redirects to [this](https://www.imdb.com/search/title/&countries=!af,!pk) url.

It would be great if the script is executed when the "search" button at the bottom of the page is clicked so that I can perform a query like [this one](https://www.imdb.com/search/title/?title_type=feature&user_rating=8.0,&num_votes=50000,&runtime=180,) for example and the script would add [countries parameter automatically](https://www.imdb.com/search/title/?title_type=feature&user_rating=8.0,&num_votes=50000,&countries=!in&runtime=180,) to exclude results from the countries set in script

**Comment by darkred** [comment]
> There's a small problem though, now the advance title search page is not accessible to select other parameters (eg: ratings) as it always redirects to this url.

Change the `if` line into:

```javascript
> if (!window.location.href.includes(countriesToIgnore && window.location.href !== 'https://www.imdb.com/search/title/'))) {
```

---

> It would be great if the script is executed when the "search" button at the bottom of the page is clicked 

The way I see it, if the default functionality of the "submit" becomes disabled, 
then my script will have to manually parse all the parameters in the page,  in order to redirect to the proper search results page. 
That's too much for me.
I'm sorry I can't assist you any further. Maybe you'd like to make a request in https://greasyfork.org/en/discussions/requests

**Comment by NitroV** [comment]
It's alright! Thanks for your effort. :)

**Comment by NitroV** [comment]
> The way I see it, if the default functionality of the "submit" becomes disabled,
> then my script will have to manually parse all the parameters in the page, in order to redirect to the proper search results page.

Does this problem still exist even if you take the latter approach I mentioned in the first post? That is;

> modify the function of default "countries" field in the advanced title search page to EXCLUDE results from selected country instead of only including results from that country.

Basically to invert the function of country selection that is offered by IMDB. For example, when a country is selected from the list, it already adds `&countries=xy` (notice the lack of "!") parameter to the search result URL.

If you were to somehow reverse engineer that function to exclude results from that country (by adding "!" in front of the  country code) it should technically not require parsing all parameters, right?

Please consider revisiting this script in the future as there are tons of threads related to this very thing in imdb forums and many people would find such script useful :) I already posted a request on greesyfork as well, will keep eye on there too.
