### ISSUE TITLE
Hide Porn torrents

### ISSUE THREAD

**Issue by Rootzpower** [darkred/Userscripts#16]
Hi!
Great script

Its possible to add an option to hide porn?

Its annoying browsing for torrents and see to much porn torrents.

**Comment by darkred** [comment]
This script offers what you want and much more: [RARBG Advanced Filters](https://greasyfork.org/en/scripts/29661-rarbg-advanced-filters)

**Comment by Rootzpower** [comment]
Too much functions and settings.
What i real need it's just a simple script to hide porn nothing more.
BTW thanks
