### ISSUE TITLE
[Google youtube search link] Not showing up if the "videos" tab is selected

### ISSUE THREAD

**Issue by alpe12** [darkred/Userscripts#20]
If I do a search, the "youtube" tab appears correctly right after "videos".
But if I click on "videos" the "youtube" tab doesn't show.

**Comment by darkred** [comment]
I've fixed this in the new version (and also for the "News" tab).
Please confirm it's ok for you.


PS. It doesn't work in the "Images" because all selectors have become different in that. Keeping that as in mind as TODO.

**Comment by alpe12** [comment]
Yes, it is working.
Thanks.

**Comment by darkred** [comment]
Previous version wasn't working in localized Google Search pages. 
Fixed in new version and now it also works in 'Images' tab again.
