### ISSUE TITLE
[FF for Desktop] GM_xmlhttpRequest is not defined

### ISSUE THREAD

**Issue by brunnopleffken** [darkred/Userscripts#21]
I'm using FF Nightly v87 and running Greasemonkey v4.11.
Accessing https://hg.mozilla.org/mozilla-central/pushloghtml?startdate=1+day+ago&enddate=now with Greasemonkey + Firefox for Desktop enabled I get the following error in the console:

```
Script error in [Greasemonkey script darkred/Firefox for desktop - list fixed bugs in Mercurial; version 4.2.9]:
ReferenceError: GM_xmlhttpRequest is not defined
```

...and the script doesn't work at all.

**Comment by darkred** [comment]
Sorry but as I write in the README:

> Greasemonkey -any version- is not supported.
