### ISSUE TITLE
[Markdown toolbar for GreasyFork] Need a new @include to work on feedback pages

### ISSUE THREAD

**Issue by decembre** [darkred/Userscripts#23]
Need this include to work on feedback pages (tested): 
// @include 

That's when we post the first feedback.
After that's all post are "discussion"...

Another thing:
I can't see the toolbar here (script normally working on it):
<a href="">Edit our Feedback</a>

Note:
On Feedback of scripts, I notice the need to refresh the page after posting to see the "markdown toolbar":
When we just have posted a feedback, the "edit" button appear on it (but it don't work!).
And the toolbar is not visible on the textarea under it.
Reappear at refresh (no edit button on our previous post).

I Post it too greasyfork:
<a href="https://greasyfork.org/en/scripts/422887-markdown-toolbar-for-greasyfork/discussions/78139">Need this include to work</a>

**Comment by darkred** [comment]
Firstly please update to the new version, I made some improvements.

---

> I Post it too greasyfork:

Please post all your issues here, not in greasyfork, help me keep track of your feedback in a single place.

---

> On Feedback of scripts, I notice the need to refresh the page after posting to see the "markdown toolbar"

Yes, I'll try to fix it.

**Comment by decembre** [comment]
Thanks !

Some precision:
When i post a reply, the toolbar is not here (and the edit button is present on my post).
Refresh the page don't change that (as the Edit button is present).
But if i click the Edit button, the toolbar is here.

Refresh after 5 minutes, the Edit button is gone and the toolbar reappear......

**Comment by darkred** [comment]
Please update to the new version. It should be fixed.

**Comment by darkred** [comment]
In the latest version everything should work fine now. Please test.
