### ISSUE TITLE
Bug with Instagram_-_visible_images_counter

### ISSUE THREAD

**Issue by thinkpad4** [darkred/Userscripts#24]
Thanks for reporting a bug! ⛰
(Instagram_-_visible_images_counter)
When this script is enabled it causes IG to a dialog box to popup in the browser.  
3. It is caused by the script cause when I disable the script the problem stops

![2021-03-09_204925](https://user-images.githubusercontent.com/6820014/110563442-52e77c80-8119-11eb-976c-d27fe2cfe4e7.png)

That box pops up when visiting my profile, when a story video ends, looking at followers, or followed, etc.

Chrome 88 Violentmonkey
2.12.9

**Comment by darkred** [comment]
I had used 3 [`alert()`](https://www.w3schools.com/jsref/met_win_alert.asp) lines for debugging, but I forgot to comment out the last one, sorry. 
Fixed in the new version 👍

**Comment by thinkpad4** [comment]
@darkred Ok, the fix got rid of the popup thing but now when the script is enabled and I click on my folowers or following instead of the list showing it just refreshes the page.  So there is still something in the script that is causing a issue.

**Comment by darkred** [comment]
It should be fixed in the new version.

**Comment by thinkpad4** [comment]
@darkred It's working perfect now.  Thank you very much
