### ISSUE TITLE
Enable the The "Markdown toolbar" only when the Markdown button is checked

### ISSUE THREAD

**Issue by decembre** [darkred/Userscripts#25]
It's seem the form accept always the markdown formatting when i have not choose it (HTML checked).
Maybe that's explain why i have some problem when i want a line break that not be applied.
So, it should be great and less confused, if the Markdown Toolbar work only when "Markdown" is checked

**Comment by darkred** [comment]
Ok, I'll see what I can do.

**Comment by decembre** [comment]
;-)

**Comment by darkred** [comment]
To clarify:
what you ask is, when you switch to the `HTML` radio button:
the toolbar functionality to be disabled? 
or the toolbar itself to become hidden?

Note that the original script didn't offer neither of these two.
It just auto-clicked all 'Markdown' radio buttons in the page.

**Comment by decembre** [comment]
> 
> 
> when you switch to the `HTML` radio button:
> the toolbar functionality to be disabled?


Yes, because when we are on HTML , Markdown formatting can be applied, with some strange effects (i suppose).
> 
> Note that the original script didn't offer neither of these two.
> It just auto-clicked/switched to all 'Markdown' radio buttons in the page.


Yep, i know... do your possible.
;-)

**Comment by darkred** [comment]
Sorry, but I'll have to disappoint you here, I can't manage to do what you ask, although I tried.
I'm closing this.

Sidenote: by the way, the method I currently use to hide the toolbar when switching to the `Preview` tab is unfortunately flawed:
sometimes the toolbar might not be hidden, or isn't restored afterwards.
And it's hidden earlier than expected: it's hidden immediately, as you click `Preview` - not when the Preview tab itself gets the red focus.

---

Please reply to: https://github.com/darkred/Userscripts/issues/23#issuecomment-797776473

Is the toolbar showing up when pressing Edit ?

**Comment by decembre** [comment]
> 
> 
> Please reply to: [#23 (comment)](https://github.com/darkred/Userscripts/issues/23#issuecomment-797776473)
> 
> Is the toolbar showing up when pressing Edit in all cases for you ?

Yes!
<a href="https://greasyfork.org/en/scripts/422887-markdown-toolbar-for-greasyfork/discussions/78139#comment-190530">That's OK for the Both Forms!</a>

> 
> 
> Sorry, but I'll have to disappoint you here, I can't manage to do what you ask, although I tried.
> I'm closing this.

Ok not a problem:
It seems not so easy to code....
Anyway thanks for your work... in progress
;-)
PS:
Jason Barnabe can add these toolbars (Markdon and HTML) if i wanted (but it seems i remember i don't... )

**Comment by darkred** [comment]
Ok, thanks for the feedback.
