### ISSUE TITLE
(Reddit Infinite Scrolling) Ability to come back to certain scroll 

### ISSUE THREAD

**Issue by benyaminl** [darkred/Userscripts#42]
Hello, is there anything possible to make jscroll unlimited scroll reddit works like RES unlimited scroll so we has #id link that can be return back without scrolling again or the API make it not possible at all? Thank you.

**Comment by darkred** [comment]
> works like RES unlimited scroll so we has #id link that can be return back without scrolling again or the API make it not possible at all

Could you please explaining what you mean? I don't quite understand.
And could you give an actual example reddit URL?

**Comment by benyaminl** [comment]
So everytime when we hit the scroll part, RES add anchor URL so when we press back button from browser on keyboard, it will end on the same place like last time. 

eg you scoll till page 3 of never ending/infinite scroll, go to some link, and go back, you will end up with first pages not 3 page data shown. I think it will be convenient if we return to the page you were last on when hitting "back" button. 

I hope it's clear enough.

**Comment by darkred** [comment]
Ok, I understand know.

Sorry, unfortunately I can't fulfill this request, as it's far too complicated to replicate that RES functionality, and out of the purpose of this simple script: this was meant merely to provide a configuration for jScroll to use on reddit.

I also use RES and it's perfect, a must-have extension.

**Comment by benyaminl** [comment]
Alright... Okay... Thank you

**Comment by darkred** [comment]
I see that you reacted with a laugh emoji to my reply... If you think it's a simple task to replicate the RES functionality, you are free to add it in your own fork, or write a script from scratch.

I wrote that "RES is perfect" in the sense that it's already full-featured, and their devs have done an incredible job, really advanced stuff. I am nowhere nearly their level of knowledge.

**Comment by benyaminl** [comment]
> 
> 
> I see that you reacted with a laugh emoji to my reply... If you think it's something trivial to replicate the RES functionality, you are free to add it in your own fork, or write a script from scratch.
> 
> I wrote that "RES is perfect" in the sense that it's already full-featured, and their devs have done an incredible job, really advanced stuff. I am nowhere near their level of knowledge.

Yeah yeah, I think about to make one, I mean the laugh emoji is kind of real condition that it is complicated, and no simple mater to implement. 
Yeah RES is full featured but the problem is RES always run on background even when we are not on Reddit, so wasting resources, that's why I scrape many userscript for it. Anyway thanks for replying.

**Comment by darkred** [comment]
Ok, no problem, misunderstanding then, all cool 😎 
If you make a script for it, please keep me posted, it would be informational for me 👍
