### ISSUE TITLE
[RARBG - torrent and magnet links] Possible to make this script compatible with another autopagerizing script?

### ISSUE THREAD

**Issue by travibe** [darkred/Userscripts#47]
### Please ensure:

- [X] I included in the issue title the script name I'm referring to.
- [X] Before you request from me to write a new script for you, check in https://greasyfork.org/en/scripts and https://openuserjs.org/ : what you ask might be there already.

### Description

Hi! Before writing anything else, I want to tell you how much your script has simplified using RARBG For me and it is just phenomenal! I also use an additional script that autopagerizes Just about any site and when combined with your script, your magnet and torrent links only appear for the links that would be on the physical first page (Which in all reality is probably working exactly as it should.), But then stop appearing where All the torrents that begin on page 2 begin appearing. I don't know if I'm explaining this very well but I'm just curious if you can find a way to have your script coincide or work hand-in-hand with the autopager script and continue to Show the torrent and magnet links continuously. The script that I am using is "Super_preloaderPlus_one_New"  Which can be found https://github.com/machsix/Super-preloader . I don't Want to appear ungrateful, I'm more curious if it would be a simple fix for you to include this feature. If so that would be fantastic otherwise ignore all of this and just keep making your awesome scripts! Thank you so much 👍👍👍👍👍

### Example URL

https://

**Comment by darkred** [comment]
Thanks for your kind words. 

Your feature request is in essence the same as [this one](https://greasyfork.org/en/scripts/23493-rarbg-torrent-and-magnet-links/discussions/16157) in GreasyFork. Unfortunately I cannot help you with the script that you mention, as I couldn't help using jScroll, a jQuery plugin) -see link-.

What you ask, is the script to re-execute on every new pagination event (only on the paginated content).
Probably Intersection Observer API would be useful, but I can't help you. I'm sorry.

Maybe try making a request in [greasyfork.org/en/discussions/requests](https://greasyfork.org/en/discussions/requests).

**Comment by darkred** [comment]
Click [here](https://gist.github.com/darkred/7e88691e99a690fb4a5a32ed4e568460/raw/143f9ffe8f673a8bfd3cfd70ac8d731a4d382796/RARBG%2520-%2520torrent%2520and%2520magnet%2520links.user.js) to install the modified version I made for you 👍

[Gist](https://gist.github.com/darkred/7e88691e99a690fb4a5a32ed4e568460)

**Comment by travibe** [comment]
I have installed it and deactivated the older version to avoid there being now two columns of torrent and magnet links 🙄.  However, it continues to appear identical to what was already occurring with the older version. I hate being the problem here, and I want you to hear me loud and clear that you have impressed the living hell out of me by 1) doing this so rapidly, and 2) going back on your initial decision for whatever reason and spending your own precious time helping an absolute stranger . My hat is off to you, sir.

Is there something completely obvious and stupid I should be doing that you can think of that I may not be? I don't want your effort to be wasted on behalf of my ignorance.

**Comment by darkred** [comment]
> going back on your initial decision for whatever reason

Kindness is the key for me 🙂 

---

As in in the screen capture below, the script is working fine for me with a fresh Chrome profile, with only Violentmonkey beta/Tampermonkey beta (and uBO) on `https://rarbgproxy.org/torrents.php` :

<details>
<summary>Screen capture:</summary>

![](https://user-images.githubusercontent.com/723651/163968393-85cf93ac-ef65-4822-8e73-6eed52fff898.gif)
</details>

The initial script needs to be disabled of course, because the custom one has a slightly different `@name`.

First make sure the initial script doesn't run too. Then, if the problem still persists, give: browser version, script manager, test URL, i.e. all possible details so that I can recreate it.
