### ISSUE TITLE
[ProtonMail_-_remove_forced_signature] Not work

### ISSUE THREAD

**Issue by wuniversales** [darkred/Userscripts#48]
### Please ensure:

- [X] I included in the issue title the script name I'm referring to.
- [X] I performed a search of the [issue tracker](https://github.com/darkred/Userscripts/issues) and in the relevant Greasyfork [feedback page](https://greasyfork.org/en/users/2160-darkred?sort=updated) to avoid opening a duplicate issue.
- [X] The bug is caused by the script itself. It doesn't happen if I disable the script, or in a fresh browser profile.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Describe the problem and how to replicate it

Not work

### Example URL

¿?

### Script Manager

Tampermonkey

### Browser(s) used

Chrome latest version

**Comment by darkred** [comment]
The iframe selector had changed after recent html changes. Updated in the new version. Thanks.
