### ISSUE TITLE
Is this script working?

### ISSUE THREAD

**Issue by KaddishSaint** [darkred/Userscripts#5]
Is this script working? I tried installing to replace the terrible asterisks on Twitter and nothing happened. Apparently, it did not work.

**Comment by darkred** [comment]
What script, with what script manager, in what browser??
What are you talking about??

**Comment by KaddishSaint** [comment]
This script: https://github.com/darkred/Userscripts/tree/master/Twitter_-_add_unread_notifications_count_in_the_tab_title

Violentmonkey

Chromium

**Comment by darkred** [comment]
First of all, in the future, please, make proper reports if you want someone to help you.
You haven't provided literally any relevant info in the OP.

---
Anyway;

the script 'Twitter - add unread notifications count in the tab title'
works ok in Tampermonkey
and in GreaseMonkey (even with 4.0 in FF 57),
that I use.

There has been a recent change in Twitter's layout, and so,
whenever you have new more than 20 tweets, 
the unread tweets count is changed into an asterick 
and after that  there's no unread count available  on the page, for the script to use.

Therefore the script works fine.
