### ISSUE TITLE
[ProtonMail - remove forced signature] Feature request: remove the entire "protonmail_signature_block" div rather than just the text within

### ISSUE THREAD

**Issue by Ketchup901** [darkred/Userscripts#50]
### Please ensure:

- [X] I included in the issue title the script name I'm referring to.
- [X] Before you request from me to write a new script for you, check in https://greasyfork.org/en/scripts and https://openuserjs.org/ : what you ask might be there already.

### Description

Thank you for making this script!

However there is still an empty div at the bottom of each sent email which is visible if you inspect the HTML. It would be nice if you found a way to remove it entirely. Thanks!

### Example URL

https://mail.proton.me

**Comment by darkred** [comment]
You're welcome! And thanks for your report. What you describe is not a new feature but how the script should work. 
Unfortunately with my last commit the script breaks when there's no user signature.
I just delisted the script in greasyfork.
I'll update when I find a solution.

**Comment by darkred** [comment]
Please update to the new version, it's working fine now.
