### ISSUE TITLE
[Instagram - visible images counter] Broken by IG update?

### ISSUE THREAD

**Issue by gitdine** [darkred/Userscripts#52]
### Please ensure:

- [X] I included in the issue title the script name I'm referring to.
- [X] I performed a search of the [issue tracker](https://github.com/darkred/Userscripts/issues) and in the relevant Greasyfork [feedback page](https://greasyfork.org/en/users/2160-darkred?sort=updated) to avoid opening a duplicate issue.
- [X] The bug is caused by the script itself. It doesn't happen if I disable the script, or in a fresh browser profile.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Describe the problem and how to replicate it

Recently stopped working properly, now always shows 0/XXX images no matter how much you scroll. 
Also causing bugs with navigation, prevents opening stories and navigating from image -> profile (bugs disappear once script is disabled.)

### Example URL

https://www.instagram.com/zuck/

### Script Manager

Violentmonkey 2.13.1

### Browser(s) used

Firefox 105.0.1

**Comment by darkred** [comment]
Hi @gitdine . Thanks for the report. Sorry for the late reply but I had some issues.
Please try the [new version](https://github.com/darkred/Userscripts/raw/4b864f1b1fe86441d9846073dd02434160aaf447/Instagram_-_visible_images_counter/Instagram_-_visible_images_counter.user.js) and report if you still have any issues.
I delisted the script from greasyfork. If it's working ok for you, I'll restore it.

**Comment by gitdine** [comment]
> Hi @gitdine . Thanks for the report. Sorry for the late reply but I had some issues. Please try the [new version](https://github.com/darkred/Userscripts/raw/4b864f1b1fe86441d9846073dd02434160aaf447/Instagram_-_visible_images_counter/Instagram_-_visible_images_counter.user.js) and report if you still have any issues. I delisted the script from greasyfork. If it's working ok for you, I'll restore it.

Just tested and everything fully working again, thanks.

**Comment by gitdine** [comment]
> > Hi @gitdine . Thanks for the report. Sorry for the late reply but I had some issues. Please try the [new version](https://github.com/darkred/Userscripts/raw/4b864f1b1fe86441d9846073dd02434160aaf447/Instagram_-_visible_images_counter/Instagram_-_visible_images_counter.user.js) and report if you still have any issues. I delisted the script from greasyfork. If it's working ok for you, I'll restore it.
> 
> Just tested and everything is fully working again, thanks.
Actually spoke too soon, the navigation bug is still present,
E.g.
https://www.instagram.com/p/CkIzKagLyj3/
When I click the link to go to his profile, nothing happens.
With the script disabled, I'm taken to the profile.

**Comment by darkred** [comment]
Ok. Please test [new version](https://github.com/darkred/Userscripts/raw/5b708a471ac528d491245115aa6e57f08802bdb0/Instagram_-_visible_images_counter/Instagram_-_visible_images_counter.user.js). I believe it's all fixed now. Please report if you have any other issues.

**Comment by gitdine** [comment]
> Ok. Please test [new version](https://github.com/darkred/Userscripts/raw/5b708a471ac528d491245115aa6e57f08802bdb0/Instagram_-_visible_images_counter/Instagram_-_visible_images_counter.user.js). I believe it's all fixed now. Please report if you have any other issues.

Yep everything is fixed now.

**Comment by darkred** [comment]
Glad to know! So, I just restored the script in GreasyFork. Please make a follow-up comment in [GF](https://greasyfork.org/en/scripts/11635-instagram-visible-images-counter/discussions/150996) that all is fixed.

**Comment by darkred** [comment]
Fixed in the new version.
