### ISSUE TITLE
Show date in the tooltip in ISO time format (RARBG - convert torrent timestamps to relative format)

### ISSUE THREAD

**Issue by mzso** [darkred/Userscripts#6]
Hi!

I'd much prefer to have the date in this format , rather then the bad ambiguous format which is currently used. (This is what rarbg actually uses)
Maybe an option for it could be added (via greasemonkey) if the current format must be kept.

**Comment by darkred** [comment]
Hi.

I've just uploaded a new version based on your feedback.
I used `.format()` instead of `.toISOString()` because the former maintains the local timezone offset, while the latter displays them at timezone 0.
_If you prefer otherwise, uncomment line 53 and comment out line 54._

**Comment by mzso** [comment]
[**@darkred**](https://github.com/darkred) commented on [2018. ápr. 16. 18:13 CEST](https://github.com/darkred/Userscripts/issues/6#issuecomment-381660974 "2018-04-16T16:13:11Z - Replied by Github Reply Comments"):
> Hi.
> 
> I've just uploaded a new version based on your feedback.  

Thanks. Though there might be some issue with this:
![clipboarder 2018 04 16](https://user-images.githubusercontent.com/4479090/38822193-f775d95e-41a2-11e8-8087-ce16409444fe.png)

It doesn't appear in a very user-friendly way. I was expecting: YYYY-MM-DD HH:MM
Not sure what to make of the 16:40:22+02:00 part. 16:40 plus two hours is in the future, so clearly wrong. Plus it shows two hours ago anyway. (Or does that mean two minutes? Why? Or timezone offset?) 

> 
> I used `.format()` instead of `.toISOString()` because the former maintains the local timezone offset, while the latter displays them at timezone 0.  
> 
> _If you prefer otherwise, uncomment line 53 and comment out line 54._

Ummm. So the times were wrong before? (I'm not in timezones 0)
If yes, it's good that it was fixed, but my issue was with the presentation of the time

**Comment by darkred** [comment]
You asked to "show date in the tooltip in ISO time format".
ISO time format is the international standard ISO 8601 notation. 
And, based on the https://en.wikipedia.org/wiki/ISO_8601 standard that's how it's displayed with combined date and time in UTC.

But, you, by "ISO time format" you meant something **irrelevant** to the ISO standard, and that was not been shown in your too short issue report...

_In the feature, please don't make others have to guess what you ask, be more specific._

-----------

Anyway, the"+02:00" means that  the `16:40:22+02:00` is a timestamp displayed in timezone UTC +2 (i.e. 2 hours ahead of UTC).
(I see you're in France, based on your last comment. UTC +2 is France's timezone)

The times were always ok. 
It's just that now it displays your local timezone designator in the end of the tooltip.

--------------

I uploaded a new version with what your asked.

**Comment by mzso** [comment]
It's not irrelevant. The article shows the very same format in the "[calendar dates](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates)" and the "[times](https://en.wikipedia.org/wiki/ISO_8601#Times)" sections.
I didn't expect "Combined date and time in UTC", it's an odd looking thing.

> (I guess you're in France, based on "ápr" in your last comment . UTC +2 is France's timezone)

No, but the same timezone.

> I just uploaded a new version with what your want.

Thanks!
