### ISSUE TITLE
Set a limit to relative time format (RARBG - convert torrent timestamps to relative format)

### ISSUE THREAD

**Issue by mzso** [darkred/Userscripts#7]
Hi!

I think the relative format looses practicality above a year. So I think torrents older than a year should retain showing the date. Year sized granularity is is pretty large.

**Comment by darkred** [comment]
I strongly disagree.
I prefer `2 years` instead of e.g. `2016-09-24 22:22:13`.
In fact that's why I wrote this script: to stop seeing **all** timestamps, not some only.

Anyway, you could have this by changing line 47 into:
```javascript
			if (temp2.fromNow().indexOf('years') === -1){
				dates[i].innerText = temp2.fromNow();
			}
```
and changing line 69 into:
```javascript
		var temp3 = moment(dates[i].title).fromNow();
		if (temp3.indexOf('years') === -1){
			dates[i].innerText = temp3;
		}
```

**Comment by mzso** [comment]
[**@darkred**](https://github.com/darkred) commented on [2018. ápr. 16. 18:44 CEST](https://github.com/darkred/Userscripts/issues/7#issuecomment-381670464 "2018-04-16T16:44:01Z - Replied by Github Reply Comments"):
> I strongly disagree.  
> 

Oh, well...
> I prefer `2 years` instead of e.g. `2016-09-24 22:22:13`.  
> 
> In fact that's why I wrote this script: to stop seeing **all** timestamps, not some only.
> 
> * * *
> 
> Anyway, you could have this by changing line 47 into:
> 
> <div class="highlight highlight-source-js"><pre>			<span class="pl-k">if</span> (<span class="pl-smi">temp2</span>.<span class="pl-en">fromNow</span>().<span class="pl-c1">indexOf</span>(<span class="pl-s"><span class="pl-pds">'</span>years<span class="pl-pds">'</span></span>) <span class="pl-k">===</span> <span class="pl-k">-</span><span class="pl-c1">1</span>){
> 				dates[i].<span class="pl-smi">innerText</span> <span class="pl-k">=</span> <span class="pl-smi">temp2</span>.<span class="pl-en">fromNow</span>();
> 			}</pre></div>
> 
> and changing line 69 into:
> 
> <div class="highlight highlight-source-js"><pre>		<span class="pl-k">var</span> temp3 <span class="pl-k">=</span> <span class="pl-en">moment</span>(dates[i].<span class="pl-c1">title</span>).<span class="pl-en">fromNow</span>();
> 		<span class="pl-k">if</span> (<span class="pl-smi">temp3</span>.<span class="pl-c1">indexOf</span>(<span class="pl-s"><span class="pl-pds">'</span>years<span class="pl-pds">'</span></span>) <span class="pl-k">===</span> <span class="pl-k">-</span><span class="pl-c1">1</span>){
> 			dates[i].<span class="pl-smi">innerText</span> <span class="pl-k">=</span> temp3;
> 		}</pre></div>

Hmm... I can't seem to find what to change exactly. The script failed after making changes

Line 47 is this: var temp2 = moment.tz(dates[i].innerText, serverTimezone).tz(localTimezone);
So, I only need to change this line with the new code?

Line 69 is a start of a for cycle so I can't possible only need to replace that line.

**Comment by darkred** [comment]
You have confused the line numbers.
I'm referring to the [2018.4.16](https://github.com/darkred/Userscripts/blob/ee9165831dc427a3a628dde62b5f28752af9c495/RARBG_-_convert_torrent_timestamps_to_relative_format/RARBG_-_convert_torrent_timestamps_to_relative_format.user.js) version.

line 47: `dates[i].innerText = temp2.fromNow();`
line 69: `dates[i].innerText = moment(dates[i].title).fromNow();`

**Comment by darkred** [comment]
Of course, my above suggestions are the simplest I could think of. 
But, I believe they should work fine for you.
