### ISSUE TITLE
(RARBG torrent detail pages - rearrange entries and various visual tweaks) Suggestion: Recommended section should link to imdb ID search

### ISSUE THREAD

**Issue by mzso** [darkred/Userscripts#8]
Hi!

I think it would be better if the recommended torrents (with the series of covers) would link to this instead of an arbitrary version of the movie.

**Comment by darkred** [comment]
What is this? A feature request for an existing script of mine, or you ask for a new script?
In any case, please be more specific.

https://github.com/darkred/Userscripts/blob/master/CONTRIBUTING.md#how-to-report-issues-or-make-requests

**Comment by mzso** [comment]
Oops. While editing the comment I edited out rarbg from it... I meant it as tweak of rarbg for the RARBG_torrent_detail_pages_-_rearrange_entries_and_various_visual_tweaks script. (Though the "recommended" section only appears on the torrents page)

**Comment by darkred** [comment]
I prefer the 'Recommended' the way it currently is,
to link to torrent pages, not IMDb search.

Nevertheless I could provide you with a code snippet with what you want, to manually add to the script, 
but you'll have to wait for the next two months, because I won't have access to my PC until then.

**Comment by mzso** [comment]
[**@darkred**](https://github.com/darkred) commented on [2019. febr. 15. 19:03 CET](https://github.com/darkred/Userscripts/issues/8#issuecomment-464143581 "2019-02-15T18:03:55Z - Replied by Github Reply Comments"):
> I prefer the 'Recommended' the way it currently is,  
> to link to torrent pages, not IMDb search.
> 
> Nevertheless I could provide you with a code snippet with what you want, to manually add to the script,  
> but you'll have to wait for the next two months, because I won't have access to my PC until then.

I see. That would be nice.

**Comment by darkred** [comment]
I'm finally back. 
Here is the snippet that you asked:

```javascript
const isOnTorrentListPage = window.location.href.includes('torrents.php');
if (isOnTorrentListPage) {
	let entries = document.querySelectorAll('a[onmouseover~="return"]');       
	for (let i = 0; i < 8; i++) {                                              
		let temp = String(entries[i].onmouseover);
		temp = temp.match(/([a-zA-Z0-9\.]*[0-9]{4})\./)[1].replace(/\./g,' ');
		entries[i].href = 'https://www.imdb.com/find?q=' + temp;
	}
}
```

**Comment by mzso** [comment]
[**@darkred**](https://github.com/darkred) commented on [2019. máj. 1. 01:15 CEST](https://github.com/darkred/Userscripts/issues/8#issuecomment-488148504 "2019-04-30T23:15:11Z - Replied by Github Reply Comments"):
> I'm finally back.  
> Here is the snippet that you asked:
> 
> ```js
> const isOnTorrentListPage = window.location.href.includes("torrents.php");
> if (isOnTorrentListPage) {
>   let entries = document.querySelectorAll('a[onmouseover~="return"]');
>   for (let i = 0; i < 8; i++) {
>     let temp = String(entries[i].onmouseover);
>     temp = temp.match(/([a-zA-Z0-9\.]*[0-9]{4})\./)[1].replace(/\./g, " ");
>     entries[i].href = "https://www.imdb.com/find?q=" + temp;
>   }
> }
> ```

Thanks.

**Comment by darkred** [comment]
Better. change the last line into:
`entries[i].href = 'https://www.imdb.com/search/title?title=' + temp;`

**Comment by mzso** [comment]
Hi!
Apparently there was a misunderstanding. :) When I said "imdb ID search", I meant that to use the ID to search on rarbg. It seems far more logical to me than what they do: link to a random (usually poor) quality version of the film.
I want it to link to for (a current) example to:
https://rarbg.to/torrents.php?imdb=tt6513120
(or _even better_: https://rarbg.to/torrents.php?search=tt6513120&order=size&by=DESC but I can mod this myself)


**Instead of a particular torrent:**

https://rarbg.to/torrent/bnh4s2o

What the recommended poster thumbnail links to by default.

**Comment by darkred** [comment]
After your clarification I like your suggestion a lot.
So, I implemented it in the script. Check new version.

**Comment by mzso** [comment]
[**@darkred**](https://github.com/darkred) commented on [2019. máj. 1. 22:47 CEST](https://github.com/darkred/Userscripts/issues/8#issuecomment-488417817 "2019-05-01T20:47:04Z - Replied by Github Reply Comments"):
> After your clarification I like your suggestion a lot.  
> So, I implemented it in the script. Check new version.  
> Edit: just corrected the `@include` regex and the search by IMDb id URL pattern.

Great! 
Thanks, it works well.
