### ISSUE TITLE
Suggestion: Add GUI for filter settings

### ISSUE THREAD

**Issue by Cyberavater** [darkred/Userscripts#9]
Why not add a GUI like Adsbypasser or Mouseover Popup Image Viewer has?
https://adsbypasser.github.io/
https://w9p.co/userscripts/mpiv/
I only suggested their GUI for the setting.

**Comment by darkred** [comment]
I don't have any script that has so many settings 
that would justify creating a separate page for them.

**Comment by Cyberavater** [comment]
For GreasyFork Bullshit Filter plz add a GUI so that I can choose which types to filter.
